---
title: "power function"
author: "Jonathan Rosenblatt"
date: "November 3, 2015"
output: html_document
---

Power of 3-sigma test
```{r}
beta <- function(L, k, n) pnorm(L-k * sqrt(n)) - pnorm(- L -k * sqrt(n))
power.1 <- function(k ) 1-beta(3, k, 1)
power.5 <- function(k) 1- beta(3,k, 5)
power.10 <- function(k) 1- beta(3,k, 10)
power.20 <- function(k) 1- beta(3,k, 20)
power.100 <- function(k) 1- beta(3,k, 100)
curve(power.1, 0,5, xlab='Signal strength (k sigma)', ylab='Power')
curve(power.10, add = TRUE)
curve(power.100, add = TRUE)

pdf(file='../art/power_function.pdf')
curve(power.5, 0,5, xlab='Signal strength (k sigma)', ylab='Power')
curve(power.10, add=TRUE)
curve(power.10, add=TRUE)
curve(power.20, add=TRUE)
dev.off()
```


```{r ARL_0}
k = c(1,1.5,2,2.5,3)

ARL005 = c(17.897,48.093,127.528,379.091,1379.348)
ARL01  = c(10.422,27.429, 73.276,223.350, 842.150)
ARL02  = c(6.374, 16.416, 44.538,141.098, 559.874)
ARL03  = c(4.940, 12.517, 34.520,112.903, 465.553)

pdf("../art/fig53.pdf",width=5,height=5)

plot(k,log(ARL005),type="l",lty=1,xlab=expression(k),yaxt="n",
     ylab=expression(ARL[0]),mgp=c(2,1,0),xlim=c(1,3), 
     ylim=c(0,7.5),cex=0.8)
lines(k,log(ARL01),lty=2,cex=0.8)
lines(k,log(ARL02),lty=3,cex=0.8)
lines(k,log(ARL03),lty=4,cex=0.8)
axis(2,at=c(log(1),log(5),log(15),log(50),log(200),log(1000)),
     labels=c("0","5","15","50","200","1000"),cex=0.8)
legend(1,7.5,legend=c("lambda=0.05","lambda=0.1","lambda=0.2","lambda=0.3"),
       lty=1:4,cex=0.7)

graphics.off()
```

